modified config file

diff --git a/.github/workflows/config.yml b/.github/workflows/config.yml
--- a/.github/workflows/config.yml
+++ b/.github/workflows/config.yml
@@ -23,16 +23,23 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Check migrations
-        run: python manage.py check
-
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
+      - name: Check migrations
+        run: python manage.py check
+
       - name: Lint with flake8
+        id: flake8
+        continue-on-error: true
         run: flake8
+      - name: Check if 'Lint with flake8' step failed
+        if: steps.flake8.outcome != 'success'
+        run: |
+          echo "flake8 fails"
+          exit 1
 
       - name: Run app tests
         run: python manage.py test
@@ -41,9 +48,6 @@ jobs:
     name: Docker
     runs-on: ubuntu-latest
     steps:
-      - name: Remove docker container
-        run: docker rm oc_lettings-backend-1
-
       - name: Build the docker-compose image
         run: docker compose up --build
 
